service: petstore

provider:
  name: aws
  runtime: java
  memorySize: 1512
  timeout: 120
  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:profile, "default"}
  endpointType: REGIONAL

resources:
  Description: Example Pet Store API written with SpringBoot with the aws-serverless-java-container library

package:
  individually: true

functions:
  SpringBootPetStoreApi:
    package: 
      artifact: target/serverless-springboot2-example-1.0-SNAPSHOT-lambda-package.zip
    handler: com.amazonaws.serverless.sample.springboot2.StreamLambdaHandler::handleRequest
    events:
      - http:
          path: /{proxy+}
          method: ANY